# Version de la syntaxe que l'on souhaite pour decrire nos services et reseaux
version: '3'

# Configuration de nos services odoo et postgres 
services:
  odoo: 
    image: odoo:15
    container_name: eazy-odoo-15
    env_file: .env 
    depends_on: 
      - postgres 
    ports:
      - "8069:8069" 
    networks:
      - eazycnet 
    volumes:
      - data:/var/lib/odoo 
      - ./config:/etc/odoo
      - ./costum_addons:/mnt/extra-addons:ro,cached
    restart: always

  postgres: 
    image: postgres:15
    container_name: eazy-db-15
    env_file: .env 
    ports:
      - "5432:5432"
    networks:
      - eazycnet 
    volumes:
      - db:/var/lib/postgresql/data
volumes: 
  data:
  db:
networks: 
  eazycnet:
